### PR TITLE
Add circleci configuration

### PR DESCRIPTION
**Pull request by cpanato**
fixes: https://github.com/vgaidarji/ci-matters/issues/8

### CODE REVIEW

**Comment by vgaidarji** [comment]
@cpanato Thanks a lot for all the efforts with CircleCI integration. How do you want to proceed further so that we can merge your PR? As you can't invite me to project in Circle, will you finalize it soonish or I can use your configuration as a starting point, migrate it to CircleCI project in my profile and fix remaining issues if any?

**Comment by cpanato** [comment]
@vgaidarji you can create your own project for circleci, circle ci is basaed on repositories, we can have multiple ci-matters projects for each repo, just follow the instructions

**Comment by vgaidarji** [comment]
@cpanato cool, thanks. I'm a little bit busy at the moment. Will ping you here when I start working on this.

**Comment by vgaidarji** [comment]
Closing in favor of #16 
@cpanato thanks a lot for your initial contribution, I'll definitely mention your contribution in final merge commit 💪 🎉

**Pull request closed without merging**
